### PR TITLE
Deprecated ref function in config to service

### PR DESCRIPTION
**Pull request by RomanApunts**
Changes to config file to resolve deprecated function use "ref".

#27

### CODE REVIEW

**Comment by karser** [comment]
This PR breaks builds other than symfony 5.1 https://travis-ci.org/github/karser/KarserRecaptcha3Bundle/builds/725195469
Can you please add a decorator that takes care of compatibility?
```
use Symfony\Component\DependencyInjection\Loader\Configurator\ReferenceConfigurator;

function getService(string $id): ReferenceConfigurator {
    if (function_exists('\Symfony\Component\DependencyInjection\Loader\Configurator\service')) {
        // >= sf 5.1 forward compatibility
        return \Symfony\Component\DependencyInjection\Loader\Configurator\service($id);
    }
    return \Symfony\Component\DependencyInjection\Loader\Configurator\ref($id);
}
```

**Comment by RomanApunts** [comment]
I am not sure how to apply the modifications that you indicate, if you would be so kind as to explain the steps to follow, because i see the changes a made break another time but now in all versions of Symfony.

**Comment by karser** [comment]
the error is `Cannot redeclare getService()`. Can you please try another name? `getServiceOrRef` or something like that

**Comment by karser** [comment]
Weird. I'll take a look at this.

**Comment by karser** [comment]
The previous was because services.php was injected multiple times.
I removed the `getService` function because service/ref are one-liners. So I inlined their content for now. Tests pass.
image

**Comment by karser** [comment]
@RomanApunts thank you for your PR!

**Pull request merged**
